### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#11]
While I appreciate the efforts to make the plugin self-explanatory, it is still challenging to use effectively. Detailed documentation on how to employ AI links directly in a Note versus using them in the sidebar would be beneficial. This should include explanations of the various options, such as with or without templates, effects of the number of tokens, pros and cons of different AIs, etc. Additionally, a prominent link to this documentation in the settings and a mention of "comprehensive documentation" in the description would likely encourage more downloads.

**Do others agree?**

There are ongoing advancements in Ollama LLMs and the use of Agents, as highlighted in this video by Mathew Berman [https://youtu.be/qxyjkfzD-kE](https://youtu.be/qxyjkfzD-kE). It's unclear how such advanced features might be integrated into Obsidian, but perhaps flexibility in connecting to setups like that would suffice.

**Comment by SystemSculpt** [comment]
great insight from you as always. my next focus is definitely documentation.

i'm going to be remaking the website in entirety as well as post daily videos and updates really providing a course-like walkthrough for each and every part. i just need to outline everything from a general overview standpoint and then get into the nitty-gritty details of each part because i find this tool extremely powerful.

however, as you just mentioned, one can get lost in the amount of tools especially without there being any guidelines.

**Comment by SystemSculpt** [comment]
Documentation added at the brand new https://systemsculpt.com! Yay! Now to update the README...
