### ISSUE TITLE
Feedback on Plugin API Re-input Issue

### ISSUE THREAD

**Issue by febilogi** [SystemSculpt/obsidian-systemsculpt-ai#33]
Hi there!

First off, thank you so much for creating such a fantastic plugin! I really appreciate all the hard work that goes into it. I wanted to share a little feedback that might help with future updates.

Every time I update the plugin through the community feature, I find myself having to re-enter my OpenAI API key and reset the plugin settings. It would be great if there was a way to keep those settings intact!

Just for your info:

I'm using Windows 11.
I’m only using the OpenAI API.

Thanks again for your amazing work! Looking forward to seeing how the plugin evolves.

**Comment by SystemSculpt** [comment]
Thank you for your insight here - it is supposed to save automatically on each keypress / reload, but I definitely have had this happen a few times to me where a setting or two randomly reset to empty/default. I will look into refactoring the way settings are saved so that it's much more reliable. Keeping this issue open until it's resolved!

**Comment by febilogi** [comment]
Thank you for the feedback. I don't know if this bug is still there or not, but after I update the plugin to version 0.6.0, this doesn't happen again. Should I then turn this issue into the status "solved"?

**Comment by febilogi** [comment]
This doesn't happen in version 0.6.1 as well. It works great.
