### ISSUE TITLE
Possible Bug with / Command

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#5]
I have put the SS-Sync folder under my "templates" folder.

<img width="664" alt="folder structure in use" src="https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/15215377/05254a8f-0cb9-4465-87de-fb776f105498">

When I use the / command it only lists small number templates (The ones directly under SS-Syncs  and not Fabrric ones and only others if front matter added) not the fabric templates or any other templates.   

I note I need to add front matter to any template for it to be luisted even if its put in folder with the others.

Please check its functioning is as you intended and explain any requirements or restrictions on folders used.

**Comment by SystemSculpt** [comment]
Interesting; yes, each template must have the following properties: name, description, model, max tokens, tags. Have you updated the location of where you are calling the templates from? You need to check these 2 settings:

![image](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/146425971/50ec1d59-e5ce-4a91-aa6c-4e9041871550)
![image](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/146425971/9687b206-9bb9-45b4-913c-adc327d9a542)

1. Make sure that Show SS-Syncs is turned on
2. The template folder location is set to your custom location since I see you have put it inside of templates instead of the default SystemSculpt/Templates.

**Comment by grayerbeard** [comment]
See Below

 

David Torrens

Mobile and WhatsApp 07743 283 272
