### ISSUE TITLE
Small Enhancement: let the user scroll up while the AI answering

### ISSUE THREAD

**Issue by febilogi** [SystemSculpt/obsidian-systemsculpt-ai#50]
With every version of the plugin, I am unable to scroll up and read the AI's (beginning) response while it is generating a long text (I could just read what the AI writes and it is still too fast). Attempts to "force scroll" the chat upwards still result in it automatically returning to the bottom as each word is typed by the AI.

**Comment by SystemSculpt** [comment]
Mmm, I see what you mean - marking this as a feature instead of a bug - I will basically emulate how current ChatGPT/Claude chats work on web, where if you're scrolled to the bottom, it will follow the growth down, but if you scroll a bit up, you can view the past while it's generating without issue.

**Comment by SystemSculpt** [comment]
Fixed in today's update (live in a few hours), closing! Thanks for the enhancement suggestion, cheers.
