### ISSUE TITLE
Recording While On A Macbook Pro/ios Device + moor

### ISSUE THREAD

**Issue by rayadamas** [SystemSculpt/obsidian-systemsculpt-ai#77]
## Describe the question
Love The Product So Far. Wanted To Inquire About Recording While On A Macbook Pro/ios Device. When A Call Comes In, And I'm Recording, I've Tested That Some Of That Call Audio, Again From Taking A Call On The Laptop, Is Captured, But It's Extremely Low. Is There A Way Around This, Its A Small Issue As I Can Simply Record Bare Audio Fine, But Similar To How Apple Has Now Incorporated In-call Recording, Is The Outcome I'm Leaning Towards, Again, Not A Biggie. Also, What Kind Of Mp3 Files Does This Produce, As When I Look At Them In Finder, They Don't Play. Also, Upon Using My Openai Api Key And My Groq Api Key, My Macbook Pro Has This Consist Flash Of A Black Runtime Window, I Haven't Put Dedicated Effort Into Screen Recording This Happening, But Its Very Fast And Only Started When I Began Using Obs With Apis. Any Thoughts On What That Is Or How To Resolve It? Again, Great Work Brother This Shit Is Fire

**Comment by SystemSculpt** [comment]
Hey there!

Thanks so much for your detailed feedback! Let me address your points:

1. **Call Audio Recording**:  
   Unfortunately, capturing call audio at a higher volume isn't something we can do right now due to system limitations. We’d love to offer this, but it would require deeper system access that web and Electron apps just don’t have. For now, external recording software is your best bet.

2. **MP3 Files Not Playing in Finder**:  
   That’s odd! Could you try opening the files in VLC, IINA, or QuickTime? If they still don’t play, feel free to send us a sample file, and we’ll take a closer look. Personally, I've found that lots of audio files do not play with just regular QuickTime, but play just fine with VLC / IINA.

3. **Flashing Black Window**:  
   This sounds like a system-level issue unrelated to our app. It could be another process running in the background. If it persists outside of our app, it might be worth checking your system settings or other apps.

I really appreciate your feedback, but given the limitations and the fact that some issues seem external, we’ll be closing this for now. If anything changes or you need more help, don’t hesitate to reach out!

Thanks again for your support!
